### PR TITLE
initial json parser implementation

### PR DESCRIPTION
**Pull request by Tishj**
Inspired by Abba, I also wrote a JSON Parser 🥳 

I'm curious to know what you think of the implementation, but please don't judge it too harshly, the implementation is quite rudimentary, and it even features raw (but owning) pointers 🤮

### CODE REVIEW

**Review by Abdi-29 — APPROVED** [review]
I accepted it for now and I will have a look of your code tonight

**Comment by Tishj** [comment]
Hey thanks, but it's probably better in the future to not merge it right away, if you have yet to review it.

That's kind of what a PR is for, it's easy to make changes and have the maintainers of the repo get notified of those changes, and then once it's approved it gets merged :smile:

Now if I were to make changes I'd have to submit another PR (I think in this case I have access to merge it myself, but in general you don't)

**Comment by Abdi-29** [comment]
thank you Tishy for the info. I'll keep it in mind for the next time. i'll review in an hour

**Comment by mraasvel** [comment]
You can just revert the merge

**Comment by mraasvel** [comment]
ah, there's no way to reopen a PR on github @Tishj  can you remake the PR? I wanted to have a look as well

**Comment by Tishj** [comment]
Ah @mraasvel I'll re-open tomorrow, I just shut down my computer

**Pull request merged**
